#!/usr/bin/env python3
"""Bake `decisions/MAP.md` — where each live decision is actually cited.

The monthly stress test asks one question per OPEN decision: did this month's
reading move it? Answering that needs the opposite index from the one the repo
already has. `context/P#.md` reads decision -> choice; the corpus reads document
-> decisions cited. Nothing reads decision -> documents, so a run would grep the
whole corpus before it could start. This file is that index, committed so the
grep happens once a month instead of once a question.

    python3 decisions/build-map.py            # write decisions/MAP.md
    python3 decisions/build-map.py --check    # fail if the file is out of date

What the map holds, per decision: one row per document section that cites it,
linking at the citing line (`?plain=1#L<n>` opens GitHub's source view there),
or `인용 없음` when the corpus never mentions it. A decision with no citation is
a finding rather than a gap in the map — it is a choice nothing in the corpus
argues with.

Only `analysis/` and `comparison/` are scanned. A scouting report cites a
decision every run by construction — the tie line of every paper section — so
indexing them would bury the citations that came out of a full reading under
hundreds that came out of a sweep. The memo reaches the month's reports through
the prompt's own `grep`, bounded to the month.

Three parsers in this repo pattern-match the Decision-Log entry format, and each
keeps its own copy on purpose: `site/builder/decisions.py` runs inside the site
build with its dependencies, `linters/check-decision-refs.py` runs as a
standalone lint, and this script runs from a scheduled routine that installs
neither. The format is fixed by `context/CLAUDE.md` ("Decision-Log entry
format"); a change there lands in all three. The citation regexes below
(`_DREF`, `_DESIGNATOR`) are the lint's, copied verbatim so a token the lint
resolves is a token the map indexes.
"""

from __future__ import annotations

import glob
import os
import re
import sys

_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
_OUT = os.path.join(_REPO_ROOT, "decisions", "MAP.md")

# `#### [D5DQ] Does a sub-policy-rate contact loop earn its place? (P1) — **OPEN**`
_ENTRY = re.compile(
    r"^####\s*\[(D\d[A-Z]{2})\]\s*(.*?)\s*\(P(\d)\)(\s*—\s*\*\*OPEN\*\*)?\s*$"
)
_PILLAR_FILE = re.compile(r"^P(\d)\.md$")

# A citation: D + digit + two letters, not embedded in a longer token
# (linters/check-decision-refs.py).
_DREF = re.compile(r"(?<![A-Za-z0-9_])(D\d[A-Z]{2})(?![A-Za-z0-9])")
# Paper-internal designators — `Fig. D2` is a figure label, not a Decision
# (linters/check-decision-refs.py).
_DESIGNATOR = re.compile(
    r"(?:Fig\.?|Figure|Table|Tab\.?|Eq\.?|Equation|App\.?|Appendix|Sec\.?|Section|§)\s*$",
    re.IGNORECASE,
)

_HEADING = re.compile(r"^(#{2,3})\s+(.*?)\s*$")

_SCANNED_GLOBS = ("analysis/*.md", "comparison/*.md")

_NOTICE = (
    "Generated by `decisions/build-map.py` and committed — every monthly run\n"
    "regenerates it, so a hand edit is overwritten by the next one. Rebuild it\n"
    "after anything lands in `context/`, `analysis/` or `comparison/`."
)


class Decision:
    """One Decision-Log entry and the corpus lines that cite it."""

    def __init__(self, ident: str, title: str, pillar: int, is_open: bool):
        self.id = ident
        self.title = title
        self.pillar = pillar
        self.is_open = is_open
        self.rows: list[tuple[str, str, int]] = []  # (doc, section, lineno)


def harvest_decisions() -> list[Decision]:
    """Every live decision, in pillar order and then file order."""
    out: list[Decision] = []
    for path in sorted(glob.glob(os.path.join(_REPO_ROOT, "context", "P*.md"))):
        if not _PILLAR_FILE.match(os.path.basename(path)):  # _TEMPLATE.md and friends
            continue
        with open(path, encoding="utf-8") as fh:
            for line in fh:
                entry = _ENTRY.match(line.rstrip("\n"))
                if entry:
                    out.append(
                        Decision(
                            entry.group(1),
                            entry.group(2),
                            int(entry.group(3)),
                            entry.group(4) is not None,
                        )
                    )
    return out


def _section_label(text: str) -> str:
    """A rewrite's `###` runs `<Korean> | <English tags>` — keep the Korean half."""
    return text.split(" | ", 1)[0].strip()


def _scan_document(path: str, rel: str, index: dict[str, Decision]) -> None:
    """Record each decision this document cites, once per section."""
    with open(path, encoding="utf-8") as fh:
        lines = fh.readlines()

    section = ""
    in_fence = False
    seen: set[tuple[str, str]] = set()
    for lineno, raw in enumerate(lines, start=1):
        line = raw.rstrip("\n")
        if line.lstrip().startswith("```"):
            in_fence = not in_fence
            continue
        if not in_fence:
            heading = _HEADING.match(line)
            if heading:
                section = _section_label(heading.group(2))
                continue
        for m in _DREF.finditer(line):
            if _DESIGNATOR.search(line[: m.start()]):
                continue
            ident = m.group(1)
            decision = index.get(ident)
            if decision is None:  # retired, or a typo the lint reports
                continue
            key = (ident, section)
            if key in seen:
                continue
            seen.add(key)
            decision.rows.append((rel, section, lineno))


def _scanned_documents() -> list[str]:
    docs: list[str] = []
    for pattern in _SCANNED_GLOBS:
        for path in sorted(glob.glob(os.path.join(_REPO_ROOT, pattern))):
            rel = os.path.relpath(path, _REPO_ROOT)
            if os.path.basename(rel) in ("AUTHORING.md", "SETUP.md"):
                continue  # the track's contract, not one of its documents
            docs.append(rel)
    return docs


def build_map() -> str:
    decisions = harvest_decisions()
    index = {d.id: d for d in decisions}
    for rel in _scanned_documents():
        _scan_document(os.path.join(_REPO_ROOT, rel), rel, index)

    parts = ["# Decision map", "", _NOTICE, ""]
    citing_docs: set[str] = set()
    citations = 0
    for d in sorted(decisions, key=lambda d: d.pillar):
        suffix = " — OPEN" if d.is_open else ""
        parts += [f"## {d.id} — {d.title} (P{d.pillar}){suffix}", ""]
        if not d.rows:
            parts += ["인용 없음", ""]
            continue
        parts += ["| 문서 | 절 | 줄 |", "|---|---|---|"]
        for rel, section, lineno in sorted(d.rows, key=lambda r: (r[0], r[2])):
            citing_docs.add(rel)
            citations += 1
            label = os.path.basename(rel)
            parts.append(
                f"| [`{label}`](../{rel}?plain=1#L{lineno}) | {section} | {lineno} |"
            )
        parts.append("")

    open_count = sum(1 for d in decisions if d.is_open)
    parts += [
        "---",
        "",
        f"{len(decisions)} live decision(s), {open_count} OPEN — "
        f"{citations} citation(s) across {len(citing_docs)} document(s).",
    ]
    return "\n".join(parts) + "\n"


def main(argv: list[str]) -> int:
    body = build_map()
    if "--check" in argv:
        current = ""
        if os.path.exists(_OUT):
            with open(_OUT, encoding="utf-8") as fh:
                current = fh.read()
        if current != body:
            print(
                "[build-map] decisions/MAP.md is out of date — "
                "run `python3 decisions/build-map.py`"
            )
            return 1
        print("[build-map] clean — decisions/MAP.md matches the corpus")
        return 0
    with open(_OUT, "w", encoding="utf-8") as fh:
        fh.write(body)
    print(f"[build-map] wrote {os.path.relpath(_OUT, _REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
